### ISSUE TITLE
api.php to API.php in the Laravel 5 branch

### ISSUE THREAD

**Issue by harry-huddle** [joshrps/laravel-shopify-API-wrapper#14]
Can this be pulled across to the L5 branch, cheers.

**Comment by notflip** [comment]
Is this package working for you on L5? I'm getting the following error:

Uncaught ReflectionException: Class log does not exist

What do you mean with api.php to API.PHP?

**Comment by harry-huddle** [comment]
To be honest it's working fine for me right now, I don't get that error (I'm using 2.0.2).

I'm no longer sure why I was asking for that to be pulled into the L5 branch. 2.0.2 doesn't even have the filename capitalisation (api.php was renamed to API.php in a commit apparently).

If I remember and it's still relevant I'll open a new issue and explain in detail!
