### ISSUE TITLE
Error In installing the packages.

### ISSUE THREAD

**Issue by amankumarglobussoft** [joshrps/laravel-shopify-API-wrapper#18]
I am get error in installing this package in laravel 5.3. Is it compatible with laravel 5.3 ?
error :
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package rocket-code/shopify 2.0 exists as rocket-code/shopif
y[1.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 2.0.1, 2.0.2, dev
-l5_support, dev-master] but these are rejected by your constraint.
```

**Comment by joshrps** [comment]
I'm not sure, I'm in the process of migrating this project to my own personal account -> https://github.com/tothjmt/Laravel-Shopify maybe try that one. (https://packagist.org/packages/tothjmt/shopify)
