### ISSUE TITLE
Does this support the Embeddable SDK

### ISSUE THREAD

**Issue by danhanly** [joshrps/laravel-shopify-API-wrapper#2]
In the embeddable SDK, the OAuth is completed slightly differently, whereby the redirect address needs to redirect the parent (as it's all loaded through an iFrame).

https://docs.shopify.com/embedded-app-sdk/getting-started#oauth

**Comment by joshrps** [comment]
The wrapper will work with SDK and non-SDK apps. It is simply a tool to make server-to-server communication easier. All of the javascript and iframe techniques will need to be taken care of on your end.
