### ISSUE TITLE
Case Sensitivity src/RocketCode/Shopify/api.php

### ISSUE THREAD

**Issue by beitsafedaniel** [joshrps/laravel-shopify-API-wrapper#9]
Hi,

I used composer to bring this into my Laravel project and was getting a "Class 'RocketCode\Shopify\API' not found" error. After a quick look under the hood I saw .../src/RocketCode/Shopify/api.php was lowercase but the class name is upper case. After renaming the file to uppercase all working ok.

Just thought I'd point that out and ask if this should be updated?

**Comment by joshrps** [comment]
I can't verify that this is actually an issue - I've deployed on many case-sensitive and case-insensitive servers without issue, and nobody else has brought this up yet. Mind if I ask what the server specs are?

**Comment by beitsafedaniel** [comment]
Hi mate,

Running AWS Ubuntu 14.04 LTS AMI. Ngnix/Apache/PHP5.6. Message me directly
if you want to troubleshoot further.

D

_Daniel Murphy_
Director - Engineering

daniel@beitsafe.com
+61 7 5678 2004 | 0438 226 841
1300 604 814 | https://beitsafe.com | PO Box 36 Varsity Lakes QLD

**Comment by magnetas** [comment]
Have had the same issue on several ubuntu/macosx instances. Renaming api.php to API.php solves the issue, but that's not an option when using automated deployment (and composer update during the process).
I guess either the filename has to be changed to uppercase or class references everywhere should become lowercase.

**Comment by ghost** [comment]
Same problem here http://joxi.net/VrwYojdcdakD2X, also renaming from api.php to API.php solved problem.

**Comment by ghost** [comment]
saw that it's solved, maybe an older version of RocketCode downloaded.

**Comment by jhourlad** [comment]
This remains an issue up to now even with "rocket-code/shopify": "~2.0"

**Comment by cbjesse** [comment]
Same issue today. I'm hosting on CLOUDWAYS if that helps at all. Changing the filename did fix my issue. I didn't have the issue on my local env only on CLOUDWAYS,
